@echo off
setlocal

REM Configure external InterGen source/config paths for this API wrapper.
set "INTERGEN_SOURCE_ROOT=D:\InterGen\InterGen_master"
set "INTERGEN_CONFIG_DIR=D:\InterGen\InterGen_master\configs"
set "INTERGEN_HUMAN_MODELS_ROOT=D:\InterGen\InterGen_master\human_models"

REM Keep imports deterministic: prioritize original InterGen source tree.
set "PYTHONPATH=%INTERGEN_SOURCE_ROOT%;%PYTHONPATH%"

REM Align runtime defaults with api_1_1-style quality profile.
set "INTERGEN_RENDER_MODE=smpl"
set "INTERGEN_RENDER_BACKEND=fast"
set "INTERGEN_RENDER_PROFILE=quality"
set "INTERGEN_FPS=30"
set "INTERGEN_MAX_RENDER_FRAMES=210"
set "INTERGEN_BODY_MODEL=smplx"
set "INTERGEN_ALIGN_WITH_STICKMAN_AXES=1"
set "INTERGEN_FORCE_STICKMAN_AXES=1"

REM Optional runtime tuning.
REM set "INTERGEN_DEVICE=cuda:0"

echo INTERGEN_SOURCE_ROOT=%INTERGEN_SOURCE_ROOT%
echo INTERGEN_CONFIG_DIR=%INTERGEN_CONFIG_DIR%
echo INTERGEN_HUMAN_MODELS_ROOT=%INTERGEN_HUMAN_MODELS_ROOT%
echo INTERGEN_RENDER_MODE=%INTERGEN_RENDER_MODE%
echo INTERGEN_RENDER_BACKEND=%INTERGEN_RENDER_BACKEND%
echo INTERGEN_RENDER_PROFILE=%INTERGEN_RENDER_PROFILE%
echo INTERGEN_FPS=%INTERGEN_FPS%
echo INTERGEN_MAX_RENDER_FRAMES=%INTERGEN_MAX_RENDER_FRAMES%
echo INTERGEN_BODY_MODEL=%INTERGEN_BODY_MODEL%
echo INTERGEN_ALIGN_WITH_STICKMAN_AXES=%INTERGEN_ALIGN_WITH_STICKMAN_AXES%
echo INTERGEN_FORCE_STICKMAN_AXES=%INTERGEN_FORCE_STICKMAN_AXES%
echo.

python "%~dp0intergen_async_api.py"

endlocal
