#!/usr/bin/env bash
set -euo pipefail

# Configure external InterGen source/config paths for this CPU API wrapper.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

INTERGEN_SOURCE_ROOT="${PROJECT_ROOT}/../InterGen/InterGen_master"
if [[ ! -f "${INTERGEN_SOURCE_ROOT}/configs/model.yaml" ]]; then
  INTERGEN_SOURCE_ROOT="${PROJECT_ROOT}/InterGen/InterGen_master"
fi
if [[ ! -f "${INTERGEN_SOURCE_ROOT}/configs/model.yaml" ]]; then
  INTERGEN_SOURCE_ROOT="${PROJECT_ROOT}"
fi

INTERGEN_CONFIG_DIR="${INTERGEN_SOURCE_ROOT}/configs"
INTERGEN_HUMAN_MODELS_ROOT="${INTERGEN_SOURCE_ROOT}/human_models"

# Keep imports deterministic: prioritize original InterGen source tree.
export PYTHONPATH="${INTERGEN_SOURCE_ROOT}:${PYTHONPATH:-}"

# CPU defaults.
export INTERGEN_PORT="${INTERGEN_PORT:-8001}"
export INTERGEN_DEVICE="cpu"
export INTERGEN_RENDER_MODE="smpl"
export INTERGEN_RENDER_BACKEND="fast"
export INTERGEN_RENDER_PROFILE="fast"
export INTERGEN_FPS="20"
export INTERGEN_MAX_RENDER_FRAMES="140"
export INTERGEN_BODY_MODEL="smplx"
export INTERGEN_ALIGN_WITH_STICKMAN_AXES="1"
export INTERGEN_FORCE_STICKMAN_AXES="1"

# Lock core inference config to avoid startup drift across runs.
export INTERGEN_FIXED_CHECKPOINT="${INTERGEN_FIXED_CHECKPOINT:-${INTERGEN_SOURCE_ROOT}/../checkpoints/intergen.ckpt}"
export INTERGEN_FIXED_CFG_WEIGHT="${INTERGEN_FIXED_CFG_WEIGHT:-5.0}"
export INTERGEN_FIXED_SAMPLING_STRATEGY="${INTERGEN_FIXED_SAMPLING_STRATEGY:-ddim50}"

if [[ -z "${INTERGEN_PYTHON:-}" ]]; then
  INTERGEN_PYTHON="${HOME}/anaconda3/envs/intergen_01/bin/python"
fi
if [[ ! -x "${INTERGEN_PYTHON}" ]]; then
  if command -v python3 >/dev/null 2>&1; then
    INTERGEN_PYTHON="python3"
  else
    INTERGEN_PYTHON="python"
  fi
fi

echo "INTERGEN_SOURCE_ROOT=${INTERGEN_SOURCE_ROOT}"
echo "INTERGEN_CONFIG_DIR=${INTERGEN_CONFIG_DIR}"
echo "INTERGEN_HUMAN_MODELS_ROOT=${INTERGEN_HUMAN_MODELS_ROOT}"
echo "INTERGEN_DEVICE=${INTERGEN_DEVICE}"
echo "INTERGEN_RENDER_MODE=${INTERGEN_RENDER_MODE}"
echo "INTERGEN_RENDER_BACKEND=${INTERGEN_RENDER_BACKEND}"
echo "INTERGEN_RENDER_PROFILE=${INTERGEN_RENDER_PROFILE}"
echo "INTERGEN_FPS=${INTERGEN_FPS}"
echo "INTERGEN_MAX_RENDER_FRAMES=${INTERGEN_MAX_RENDER_FRAMES}"
echo "INTERGEN_BODY_MODEL=${INTERGEN_BODY_MODEL}"
echo "INTERGEN_FIXED_CHECKPOINT=${INTERGEN_FIXED_CHECKPOINT}"
echo "INTERGEN_FIXED_CFG_WEIGHT=${INTERGEN_FIXED_CFG_WEIGHT}"
echo "INTERGEN_FIXED_SAMPLING_STRATEGY=${INTERGEN_FIXED_SAMPLING_STRATEGY}"
echo "INTERGEN_PORT=${INTERGEN_PORT}"
echo "INTERGEN_PYTHON=${INTERGEN_PYTHON}"
echo

"${INTERGEN_PYTHON}" "${SCRIPT_DIR}/intergen_async_api_cpu.py"
