@echo off
setlocal

REM Configure external InterGen source/config paths for this CPU API wrapper.
set "SCRIPT_DIR=%~dp0"
set "PROJECT_ROOT=%SCRIPT_DIR%.."
for %%I in ("%PROJECT_ROOT%") do set "PROJECT_ROOT=%%~fI"

set "INTERGEN_SOURCE_ROOT=%PROJECT_ROOT%\..\InterGen\InterGen_master"
if not exist "%INTERGEN_SOURCE_ROOT%\configs\model.yaml" (
	set "INTERGEN_SOURCE_ROOT=%PROJECT_ROOT%\InterGen\InterGen_master"
)
if not exist "%INTERGEN_SOURCE_ROOT%\configs\model.yaml" (
	set "INTERGEN_SOURCE_ROOT=%PROJECT_ROOT%"
)

set "INTERGEN_CONFIG_DIR=%INTERGEN_SOURCE_ROOT%\configs"
set "INTERGEN_HUMAN_MODELS_ROOT=%INTERGEN_SOURCE_ROOT%\human_models"

REM Keep imports deterministic: prioritize original InterGen source tree.
set "PYTHONPATH=%INTERGEN_SOURCE_ROOT%;%PYTHONPATH%"

REM CPU defaults.
if "%INTERGEN_PORT%"=="" set "INTERGEN_PORT=8001"
set "INTERGEN_DEVICE=cpu"
set "INTERGEN_RENDER_MODE=smpl"
set "INTERGEN_RENDER_BACKEND=fast"
set "INTERGEN_RENDER_PROFILE=fast"
set "INTERGEN_FPS=20"
set "INTERGEN_MAX_RENDER_FRAMES=140"
set "INTERGEN_BODY_MODEL=smplx"
set "INTERGEN_ALIGN_WITH_STICKMAN_AXES=1"
set "INTERGEN_FORCE_STICKMAN_AXES=1"

REM Lock core inference config to avoid startup drift across runs.
if "%INTERGEN_FIXED_CHECKPOINT%"=="" set "INTERGEN_FIXED_CHECKPOINT=%INTERGEN_SOURCE_ROOT%\..\checkpoints\intergen.ckpt"
if "%INTERGEN_FIXED_CFG_WEIGHT%"=="" set "INTERGEN_FIXED_CFG_WEIGHT=5.0"
if "%INTERGEN_FIXED_SAMPLING_STRATEGY%"=="" set "INTERGEN_FIXED_SAMPLING_STRATEGY=ddim50"

set "INTERGEN_PYTHON=D:\Anaconda\envs\intergen_01\python.exe"
if not exist "%INTERGEN_PYTHON%" (
	set "INTERGEN_PYTHON=python"
)

echo INTERGEN_SOURCE_ROOT=%INTERGEN_SOURCE_ROOT%
echo INTERGEN_CONFIG_DIR=%INTERGEN_CONFIG_DIR%
echo INTERGEN_HUMAN_MODELS_ROOT=%INTERGEN_HUMAN_MODELS_ROOT%
echo INTERGEN_DEVICE=%INTERGEN_DEVICE%
echo INTERGEN_RENDER_MODE=%INTERGEN_RENDER_MODE%
echo INTERGEN_RENDER_BACKEND=%INTERGEN_RENDER_BACKEND%
echo INTERGEN_RENDER_PROFILE=%INTERGEN_RENDER_PROFILE%
echo INTERGEN_FPS=%INTERGEN_FPS%
echo INTERGEN_MAX_RENDER_FRAMES=%INTERGEN_MAX_RENDER_FRAMES%
echo INTERGEN_BODY_MODEL=%INTERGEN_BODY_MODEL%
echo INTERGEN_FIXED_CHECKPOINT=%INTERGEN_FIXED_CHECKPOINT%
echo INTERGEN_FIXED_CFG_WEIGHT=%INTERGEN_FIXED_CFG_WEIGHT%
echo INTERGEN_FIXED_SAMPLING_STRATEGY=%INTERGEN_FIXED_SAMPLING_STRATEGY%
echo INTERGEN_PORT=%INTERGEN_PORT%
echo INTERGEN_PYTHON=%INTERGEN_PYTHON%
echo.

"%INTERGEN_PYTHON%" "%~dp0intergen_async_api_cpu.py"

endlocal
