@echo off
setlocal

REM Start LODGE async API with BVH export and Blender/Rokoko retargeting enabled.
set "SCRIPT_DIR=%~dp0"
set "PROJECT_ROOT=%SCRIPT_DIR%.."
for %%I in ("%PROJECT_ROOT%") do set "PROJECT_ROOT=%%~fI"

if "%LODGE_PORT%"=="" set "LODGE_PORT=8002"
if "%LODGE_MAX_CONCURRENT_TASKS%"=="" set "LODGE_MAX_CONCURRENT_TASKS=1"

set "PYTHONIOENCODING=utf-8"
set "LODGE_SUBPROCESS_ENCODING=utf-8"
set "LODGE_SUBPROCESS_ERRORS=replace"
set "LODGE_RETARGET_ENABLED=1"
set "LODGE_BLENDER_EXE=D:\Blender_4.2\blender.exe"
set "LODGE_TARGET_FBX=D:\HumanAction_Platform\X Bot.fbx"
set "LODGE_RETARGET_MAPPING=D:\HumanAction_Platform\momask-main\assets\mapping.json"
set "LODGE_RETARGET_SCRIPT=%SCRIPT_DIR%blender_rokoko_retarget.py"
set "LODGE_MAX_RENDER_FRAMES=2000"
set "LODGE_RETARGET_MAX_RENDER_FRAMES=2000"
set "LODGE_RETARGET_RENDER_SIZE=1080x1080"
set "LODGE_RETARGET_CAMERA_DISTANCE_SCALE=1.15"

set "LODGE_PYTHON=D:\Anaconda\envs\lodge\python.exe"
if not exist "%LODGE_PYTHON%" (
	set "LODGE_PYTHON=python"
)

echo LODGE_PORT=%LODGE_PORT%
echo LODGE_MAX_CONCURRENT_TASKS=%LODGE_MAX_CONCURRENT_TASKS%
echo PYTHONIOENCODING=%PYTHONIOENCODING%
echo LODGE_SUBPROCESS_ENCODING=%LODGE_SUBPROCESS_ENCODING%
echo LODGE_SUBPROCESS_ERRORS=%LODGE_SUBPROCESS_ERRORS%
echo LODGE_RETARGET_ENABLED=%LODGE_RETARGET_ENABLED%
echo LODGE_BLENDER_EXE=%LODGE_BLENDER_EXE%
echo LODGE_TARGET_FBX=%LODGE_TARGET_FBX%
echo LODGE_RETARGET_MAPPING=%LODGE_RETARGET_MAPPING%
echo LODGE_RETARGET_SCRIPT=%LODGE_RETARGET_SCRIPT%
echo LODGE_MAX_RENDER_FRAMES=%LODGE_MAX_RENDER_FRAMES%
echo LODGE_RETARGET_MAX_RENDER_FRAMES=%LODGE_RETARGET_MAX_RENDER_FRAMES%
echo LODGE_RETARGET_RENDER_SIZE=%LODGE_RETARGET_RENDER_SIZE%
echo LODGE_RETARGET_CAMERA_DISTANCE_SCALE=%LODGE_RETARGET_CAMERA_DISTANCE_SCALE%
echo LODGE_PYTHON=%LODGE_PYTHON%
echo.

"%LODGE_PYTHON%" "%SCRIPT_DIR%lodge_async_api.py"

endlocal
