@echo off
setlocal

REM Canonical LODGE API entry point. Retarget resources are configured here,
REM while each request's skin_ids decides which final videos are generated.
set "SCRIPT_DIR=%~dp0"
set "PROJECT_ROOT=%SCRIPT_DIR%.."
for %%I in ("%PROJECT_ROOT%") do set "PROJECT_ROOT=%%~fI"

if "%LODGE_PORT%"=="" set "LODGE_PORT=8002"
if "%LODGE_MAX_CONCURRENT_TASKS%"=="" set "LODGE_MAX_CONCURRENT_TASKS=1"

set "PYTHONIOENCODING=utf-8"
set "LODGE_SUBPROCESS_ENCODING=utf-8"
set "LODGE_SUBPROCESS_ERRORS=replace"
set "LODGE_RETARGET_ENABLED=0"
set "LODGE_BLENDER_EXE=D:\Blender_4.2\blender.exe"
set "LODGE_TARGET_FBX=D:\HumanAction_Platform\X Bot.fbx"
set "LODGE_RETARGET_MAPPING=D:\HumanAction_Platform\momask-main\assets\mapping.json"
set "LODGE_RETARGET_SCRIPT=%SCRIPT_DIR%blender_rokoko_retarget.py"
set "LODGE_MAX_RENDER_FRAMES=2000"
set "LODGE_RETARGET_MAX_RENDER_FRAMES=2000"
set "LODGE_RETARGET_RENDER_SIZE=1080x1080"
set "LODGE_RETARGET_RENDER_ENGINE=BLENDER_EEVEE_NEXT"
set "LODGE_RETARGET_EEVEE_SAMPLES=32"
set "LODGE_RETARGET_RESOLUTION_PERCENTAGE=100"
set "LODGE_RETARGET_CAMERA_DISTANCE_SCALE=1.15"
set "LODGE_RETARGET_HAND_TORSO_COLLISION=1"
set "LODGE_RETARGET_HAND_TORSO_MINIMUM_WEIGHT=0.5"
set "LODGE_RETARGET_HAND_TORSO_SLICE_HALF_HEIGHT=0.05"
set "LODGE_RETARGET_HAND_TORSO_PROXY_SCALE=0.95"
set "LODGE_RETARGET_HAND_TORSO_CLEARANCE=0.025"
set "LODGE_RETARGET_HAND_TORSO_PENETRATION_THRESHOLD=0.005"
set "LODGE_RETARGET_HAND_TORSO_BLEND_FRAMES=4"
set "LODGE_RETARGET_HAND_TORSO_SMOOTHING_WINDOW=5"
set "LODGE_RETARGET_HAND_TORSO_MAX_CORRECTION=0.12"

set "LODGE_PYTHON=D:\Anaconda\envs\lodge\python.exe"
if not exist "%LODGE_PYTHON%" (
	set "LODGE_PYTHON=python"
)

echo LODGE_PORT=%LODGE_PORT%
echo LODGE_MAX_CONCURRENT_TASKS=%LODGE_MAX_CONCURRENT_TASKS%
echo PYTHONIOENCODING=%PYTHONIOENCODING%
echo LODGE_SUBPROCESS_ENCODING=%LODGE_SUBPROCESS_ENCODING%
echo LODGE_SUBPROCESS_ERRORS=%LODGE_SUBPROCESS_ERRORS%
echo LODGE_RETARGET_ENABLED=%LODGE_RETARGET_ENABLED%
echo LODGE_BLENDER_EXE=%LODGE_BLENDER_EXE%
echo LODGE_TARGET_FBX=%LODGE_TARGET_FBX%
echo LODGE_RETARGET_MAPPING=%LODGE_RETARGET_MAPPING%
echo LODGE_RETARGET_SCRIPT=%LODGE_RETARGET_SCRIPT%
echo LODGE_MAX_RENDER_FRAMES=%LODGE_MAX_RENDER_FRAMES%
echo LODGE_RETARGET_MAX_RENDER_FRAMES=%LODGE_RETARGET_MAX_RENDER_FRAMES%
echo LODGE_RETARGET_RENDER_SIZE=%LODGE_RETARGET_RENDER_SIZE%
echo LODGE_RETARGET_RENDER_ENGINE=%LODGE_RETARGET_RENDER_ENGINE%
echo LODGE_RETARGET_EEVEE_SAMPLES=%LODGE_RETARGET_EEVEE_SAMPLES%
echo LODGE_RETARGET_RESOLUTION_PERCENTAGE=%LODGE_RETARGET_RESOLUTION_PERCENTAGE%
echo LODGE_RETARGET_CAMERA_DISTANCE_SCALE=%LODGE_RETARGET_CAMERA_DISTANCE_SCALE%
echo LODGE_RETARGET_HAND_TORSO_COLLISION=%LODGE_RETARGET_HAND_TORSO_COLLISION%
echo LODGE_RETARGET_HAND_TORSO_MINIMUM_WEIGHT=%LODGE_RETARGET_HAND_TORSO_MINIMUM_WEIGHT%
echo LODGE_RETARGET_HAND_TORSO_SLICE_HALF_HEIGHT=%LODGE_RETARGET_HAND_TORSO_SLICE_HALF_HEIGHT%
echo LODGE_RETARGET_HAND_TORSO_PROXY_SCALE=%LODGE_RETARGET_HAND_TORSO_PROXY_SCALE%
echo LODGE_RETARGET_HAND_TORSO_CLEARANCE=%LODGE_RETARGET_HAND_TORSO_CLEARANCE%
echo LODGE_RETARGET_HAND_TORSO_PENETRATION_THRESHOLD=%LODGE_RETARGET_HAND_TORSO_PENETRATION_THRESHOLD%
echo LODGE_RETARGET_HAND_TORSO_BLEND_FRAMES=%LODGE_RETARGET_HAND_TORSO_BLEND_FRAMES%
echo LODGE_RETARGET_HAND_TORSO_SMOOTHING_WINDOW=%LODGE_RETARGET_HAND_TORSO_SMOOTHING_WINDOW%
echo LODGE_RETARGET_HAND_TORSO_MAX_CORRECTION=%LODGE_RETARGET_HAND_TORSO_MAX_CORRECTION%
echo LODGE_PYTHON=%LODGE_PYTHON%
echo.

"%LODGE_PYTHON%" "%SCRIPT_DIR%lodge_async_api.py"

endlocal
